### ISSUE TITLE
Firefox and Safari issue for Archive item grid image

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/directory#1]
Firefox and Safar do not show an image when using the Directory theme

<img width="1680" alt="Screenshot 2023-03-29 at 10 50 30 AM" src="https://user-images.githubusercontent.com/24760592/228434099-bcbde846-b19b-4d7d-8a51-5e154fc0f04c.png">

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2196561906/41940?folderId=3812058

**Comment by Stiofan** [comment]
I guess not many of us are using Firefox these days.  Fix will be released later today.
