### ISSUE TITLE
Error establishing a database connection on Editor 

### ISSUE THREAD

**Issue by pol76** [AyeCode/directory#2]
Happens on GD single, GD Search, GD Archive templates, and footer too. 

![image](https://github.com/AyeCode/directory/assets/25163253/5135e69c-220b-4885-a81e-4935686f0993)

I tried to purge all cache, I'm using Brave.

Need help.

**Comment by kprajapatii** [comment]
Looks like some caching issue.

- I visited the GD Single edit template and seen similar errors sent in attachment by Paolo
- Waited 1-2 mins to load template and errors disappeared and template rendered fully.
- Saved template

Now templates don't show errors even reloaded multiple times.

Could you confirm?
