### ISSUE TITLE
BS > Contact Form freezes the site

### ISSUE THREAD

**Issue by pol76** [AyeCode/directory#3]
![image](https://github.com/AyeCode/directory/assets/25163253/ab5c286c-fa0f-4cfa-8140-ae203fcd15b2)

Also is there any way to add fields? Maybe with a snippet?

**Comment by pol76** [comment]
see here: https://yesnuevo.com/vacation-rentals/condo-rosina/

**Comment by Stiofan** [comment]
fixed, will be in next release
