### ISSUE TITLE
Styles not working properly

### ISSUE THREAD

**Issue by pol76** [AyeCode/directory#4]
Blockstrap and the Directory theme don't seem to play nice with the FSE Editor, especially when it comes to styles. Like, when I set a background color: 

![image](https://github.com/AyeCode/directory/assets/25163253/ca5fc85e-a2c1-4db5-a34a-d7dc86269067)

It shows up in the backend editor:

![image](https://github.com/AyeCode/directory/assets/25163253/7cf94cf7-9893-488b-8faf-c9bf0c3a7d20)

But it doesn't appear on the front-end page at all.

![image](https://github.com/AyeCode/directory/assets/25163253/d6d2f45d-e6b1-4b15-949b-bf6a40cc70cf)

Something's off here, this can't be right.

**Comment by pol76** [comment]
It seems like all the headings are also out of sync with the style options. If you want to tweak them, you've got to do it block by block. It's a bummer that we're not able to use the global colors across the board.

**Comment by Stiofan** [comment]
most of these are fixed now, lets close this and re-open if any new ones.
